"""Add execution models for contractors

Revision ID: 5b6a9e5a5f46
Revises: 
Create Date: 2025-10-14 03:56:57.649107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b6a9e5a5f46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ausfuehrungs_reife_pruefungen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AUSFUEHRUNGSREIF', 'KLAERUNGSBEDARF', 'NICHT_AUSFUEHRUNGSREIF', name='ausfuehrungsstatusenum'), nullable=False),
    sa.Column('vollstaendigkeit_score', sa.Float(), nullable=True),
    sa.Column('detailgrad_score', sa.Float(), nullable=True),
    sa.Column('materialspezifikation_score', sa.Float(), nullable=True),
    sa.Column('schnittstellen_score', sa.Float(), nullable=True),
    sa.Column('gesamt_score', sa.Float(), nullable=True),
    sa.Column('anzahl_kritische_befunde', sa.Integer(), nullable=True),
    sa.Column('anzahl_fehlende_dokumente', sa.Integer(), nullable=True),
    sa.Column('anzahl_unklare_spezifikationen', sa.Integer(), nullable=True),
    sa.Column('empfehlung', sa.Text(), nullable=True),
    sa.Column('naechste_schritte', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('geprueft_von', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_listen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('gewerk', sa.String(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_von', sa.String(), nullable=True),
    sa.Column('validiert', sa.Boolean(), nullable=True),
    sa.Column('validiert_von', sa.String(), nullable=True),
    sa.Column('validiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schnittstellen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('gewerk_von', sa.String(), nullable=False),
    sa.Column('gewerk_zu', sa.String(), nullable=False),
    sa.Column('typ', sa.Enum('ELEKTROANSCHLUSS', 'WASSERANSCHLUSS', 'ABWASSERANSCHLUSS', 'LUEFTUNGSANSCHLUSS', 'STEUERUNGSSIGNAL', 'SCHLITZ_DURCHBRUCH', 'BEFESTIGUNG_TRAGWERK', name='schnittstellentypenum'), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('geklaert', sa.Boolean(), nullable=True),
    sa.Column('verantwortlich', sa.String(), nullable=True),
    sa.Column('plan_referenz', sa.String(), nullable=True),
    sa.Column('sud_plan_referenz', sa.String(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('geklaert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fehlende_dokumente',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pruefung_id', sa.String(), nullable=False),
    sa.Column('dokument_typ', sa.String(), nullable=False),
    sa.Column('gewerk', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('prioritaet', sa.String(), nullable=False),
    sa.Column('grund', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pruefung_id'], ['ausfuehrungs_reife_pruefungen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('dokument_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('TEXT', 'TABLE', 'METRIC', name='knowledgechunktypeenum'), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('source_reference', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dokument_id'], ['dokumente.id'], ),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_positionen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('liste_id', sa.String(), nullable=False),
    sa.Column('kategorie', sa.Enum('HEIZKOERPER', 'ROHRLEITUNGEN', 'ARMATUREN', 'LUEFTUNGSAUSLAESSE', 'KANAELE', 'SANITAERARMATUREN', 'ELEKTROKOMPONENTEN', 'DAEMMUNG', 'BEFESTIGUNG', 'SONSTIGES', name='materialkategorieenum'), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('hersteller', sa.String(), nullable=True),
    sa.Column('typ', sa.String(), nullable=True),
    sa.Column('artikelnummer', sa.String(), nullable=True),
    sa.Column('menge', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(), nullable=False),
    sa.Column('abmessungen', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('spezifikation', sa.Text(), nullable=True),
    sa.Column('quelle_dokument_id', sa.String(), nullable=True),
    sa.Column('quelle_plan_referenz', sa.String(), nullable=True),
    sa.Column('extraktionsmethode', sa.String(), nullable=True),
    sa.Column('konfidenz', sa.Float(), nullable=True),
    sa.Column('einheitspreis', sa.Float(), nullable=True),
    sa.Column('gesamtpreis', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['liste_id'], ['material_listen.id'], ),
    sa.ForeignKeyConstraint(['quelle_dokument_id'], ['dokumente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_revisionen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('dokument_id', sa.String(), nullable=False),
    sa.Column('revision_nummer', sa.String(), nullable=False),
    sa.Column('revision_datum', sa.DateTime(), nullable=False),
    sa.Column('aenderungsbeschreibung', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('vorgaenger_id', sa.String(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dokument_id'], ['dokumente.id'], ),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.ForeignKeyConstraint(['vorgaenger_id'], ['plan_revisionen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nachtraege',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projekt_id', sa.String(), nullable=False),
    sa.Column('nummer', sa.String(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('revision_von_id', sa.String(), nullable=True),
    sa.Column('revision_zu_id', sa.String(), nullable=True),
    sa.Column('betroffene_gewerke', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('geschaetzte_mehrkosten', sa.Float(), nullable=False),
    sa.Column('genehmigte_mehrkosten', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('eingereicht_am', sa.DateTime(), nullable=True),
    sa.Column('genehmigt_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekte.id'], ),
    sa.ForeignKeyConstraint(['revision_von_id'], ['plan_revisionen.id'], ),
    sa.ForeignKeyConstraint(['revision_zu_id'], ['plan_revisionen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_aenderungen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('aenderungstyp', sa.String(), nullable=False),
    sa.Column('kategorie', sa.String(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('betroffene_gewerke', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('auswirkung_material', sa.Boolean(), nullable=True),
    sa.Column('auswirkung_kosten', sa.Boolean(), nullable=True),
    sa.Column('auswirkung_zeit', sa.Boolean(), nullable=True),
    sa.Column('geschaetzte_mehrkosten', sa.Float(), nullable=True),
    sa.Column('diff_image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['plan_revisionen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_aenderungen')
    op.drop_table('nachtraege')
    op.drop_table('plan_revisionen')
    op.drop_table('material_positionen')
    op.drop_table('knowledge_chunks')
    op.drop_table('fehlende_dokumente')
    op.drop_table('schnittstellen')
    op.drop_table('material_listen')
    op.drop_table('ausfuehrungs_reife_pruefungen')
    # ### end Alembic commands ###
